### ISSUE TITLE
Failed to Connect  why ??

### ISSUE THREAD

**Issue by AhmedMansour9** [TakuSemba/RtmpPublisher#10] opened 2018-05-21 12:22 UTC

**Comment by TakuSemba** [comment] 2018-05-22 06:07
I can't to anything with the title. Could you give me more details?

・how to reproduce
・the Device you used
・sample stream you tested (or the way to make the same stream server)

**Comment by TakuSemba** [comment] 2018-05-29 04:39
im closing this issue due to the lack of information

**Closed by TakuSemba** 2018-05-29 04:39 UTC
